### PR TITLE
fix: update readme and examples

### PR DESCRIPTION
**Pull request by alikhajeh1**
- rename breakdown_json to path
- rename infracost_breakdown.json to infracost.json as we only have 1 JSON format
- show-skipped by default

### CODE REVIEW

**Comment by alikhajeh1** [comment]
@tim775 this PR looks big but it has 3 changes as mentioned in the PR desc, the Terragrunt failure is a known issue (it'll be fixed after the next Infracost CLI release).

**Review by tim775 — APPROVED** [review]
Looks good, though I think the `.github/workflows/infracost.yml` should be a single copy+pasteable code block

**Comment by alikhajeh1** [comment]
@tim775 I didn't quite follow your comment, do you mean the example in the repo readme?

**Comment by tim775** [comment]
Yeah, so we saw bigmarco create a new workflow yml and copy+paste [these lines](https://github.com/infracost/actions/blame/f506016908b609862a57fddca1c1f256ba5bdcc1/README.md#L20-L27) when I think he really just should have one code block to copy + paste.  I think the steps and explanation of what's going on are good, but not the "copy+paste this, now copy+paste this, now this..."

**Pull request merged**
