### PR TITLE
fix: add private modules to main example

### PR DESCRIPTION
**Pull request by hugorut**
I started using the `ssh-keyscan` approach suggested in the ticket. However, it turned out to be more complicated and required additional variables to be set to work across multiple steps in the pipeline. I think the original approach is easier to understand.

### CODE REVIEW

**Comment by alikhajeh1** [comment]
Is there an easy way to tweak this so users can also add multiple SSH keys? We saw a user with one key for their IAC code repos and one for their app code git repos.

**Review by alikhajeh1 — APPROVED** [review]

**Comment by alikhajeh1** [comment]
Can we also please update https://github.com/infracost/actions/tree/master/examples/multi-project-config-file and the Slack example? So this becomes part of our default docs for our integrations

**Comment by hugorut** [comment]
👍

**Comment by hugorut** [comment]
> Is there an easy way to tweak this so users can also add multiple SSH keys? We saw a user with one key for their IAC code repos and one for their app code git repos.

No for this we'd have to go down the `ssh-add` route. Let me get a working pipeline with this approach so you can see trade offs (`ssh-add` is more complex)

**Comment by hugorut** [comment]
@alikhajeh1 I've updated this to use `ssh-add` instead. All it requires to work across steps is sharing of the auth socket. Which needs to be defined as a global env. I think this works better as users can add multiple keys easier. We'll need to the docs (as per you most recent change). Let me know what you think and if you like it I'll merge and update the rest of the pipelines to use this as well.

**Comment by hugorut** [comment]
actually, I'll just merge this and the other CI systems and if we don't like it I can update it retrospectively. That way we don't have to block it going in.

**Pull request merged**
