### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by davidjeddy**
FIXED link to `Terraform/Terragrunt projects (using GitHub Actions cache` resources.

### CODE REVIEW

**Review by aliscott — APPROVED** [review]
Thanks @davidjeddy

**Comment by aliscott** [comment]
@davidjeddy thanks, I got too excited and merged it too fast. Any chance you could sign the CLA please?

**Comment by aliscott** [comment]
@davidjeddy just a reminder if you're able to sign the CLA please? 🙏

**Comment by davidjeddy** [comment]
Completed. :+1:

**Pull request merged**
