### PR TITLE
Add permissions to the example action definition

### PR DESCRIPTION
**Pull request by Octogonapus**
These are the minimum permissions needed to run Infracost. I use these on my own workflows.

### CODE REVIEW

**Comment by alikhajeh1** [comment]
This seems like a good addition, we've seen other users hit this enough times that we added [this section](https://github.com/infracost/actions#permissions-issue) to the readme but I'll leave it with @aliscott to review/decide.

**Comment by Octogonapus** [comment]
Yeah, I PR'd this because I was also confused as to what I needed and eventually found that part of the readme. I think it would be a smoother new user experience if it was simply in the example action to begin with.

**Comment by alikhajeh1** [comment]
giphy

**Comment by aliscott** [comment]
This makes a lot of sense to me, thanks @Octogonapus! I think we should include this in [all the examples](https://github.com/infracost/actions/tree/master/examples) so they are consistent.

Test failures are unrelated, so no action needed on those.

**Comment by Octogonapus** [comment]
> I think we should include this in [all the examples](https://github.com/infracost/actions/tree/master/examples) so they are consistent.

Will do.

**Review by aliscott — APPROVED** [review]
Thanks @Octogonapus this is great 🥳

**Pull request merged**
